# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\"\x17\n\x07Request\x12\x0c\n\x04text\x18\x01 \x01(\t\"!\n\x08Response\x12\x15\n\rlistOfStrings\x18\x01 \x03(\t2.\n\tTokenizer\x12!\n\nget_tokens\x12\x08.Request\x1a\t.Responseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUEST._serialized_start=17
  _REQUEST._serialized_end=40
  _RESPONSE._serialized_start=42
  _RESPONSE._serialized_end=75
  _TOKENIZER._serialized_start=77
  _TOKENIZER._serialized_end=123
# @@protoc_insertion_point(module_scope)
